"""update tables

Revision ID: 2e9bf6d4be9a
Revises: b444be3ee170
Create Date: 2025-12-16 01:49:18.750035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e9bf6d4be9a'
down_revision: Union[str, None] = 'b444be3ee170'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_transcript',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('transcript', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id')
    )
    op.drop_constraint(op.f('user_saved_videos_user_id_fkey'), 'user_saved_videos', type_='foreignkey')
    op.drop_constraint(op.f('user_saved_videos_video_id_fkey'), 'user_saved_videos', type_='foreignkey')
    op.create_foreign_key(None, 'user_saved_videos', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_saved_videos', 'video', ['video_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_saved_videos', type_='foreignkey')
    op.drop_constraint(None, 'user_saved_videos', type_='foreignkey')
    op.create_foreign_key(op.f('user_saved_videos_video_id_fkey'), 'user_saved_videos', 'video', ['video_id'], ['id'])
    op.create_foreign_key(op.f('user_saved_videos_user_id_fkey'), 'user_saved_videos', 'user', ['user_id'], ['id'])
    op.drop_table('video_transcript')
    # ### end Alembic commands ###
