"""update tables

Revision ID: 56765c5f82c3
Revises: d2571b8155d0
Create Date: 2025-12-06 00:32:53.517728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '56765c5f82c3'
down_revision: Union[str, None] = 'd2571b8155d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_saved_videos', sa.Column('test', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.drop_column('user_saved_videos', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_saved_videos', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('user_saved_videos', 'test')
    # ### end Alembic commands ###
