"""update tables

Revision ID: be27696090d5
Revises: 2e9bf6d4be9a
Create Date: 2025-12-18 23:28:12.517168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be27696090d5'
down_revision: Union[str, None] = '2e9bf6d4be9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_transcript', sa.Column('language', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_transcript', 'language')
    # ### end Alembic commands ###
